const doctorList = [
	{ name: "Joseph Williamson", department: "Cardiology", yearsOfExperience: "18 Years", fees: 20000, rating: 4.5, reviews_number: 124 },
	{ name: "Christian Nzeanorue", department: "Eye", yearsOfExperience: "8 Years", fees: 10000, rating: 3.0, reviews_number: 14 },
	{ name: "Prince Williamson", department: "Surgery", yearsOfExperience: "12 Years", fees: 8000, rating: 3.5, reviews_number: 114 },
	{ name: "Prince Ogbonna", department: "Emergency", yearsOfExperience: "6 Years", fees: 5000, rating: 2.5, reviews_number: 134 },
	{ name: "Joseph Williamson", department: "Cardiology-1", yearsOfExperience: "9 Years", fees: 4000, rating: 4.5, reviews_number: 224 },
	{ name: "Prince Williamson", department: "Surgery", yearsOfExperience: "12 Years", fees: 8000, rating: 3.5, reviews_number: 114 },
	{ name: "Prince Ogbonna", department: "Emergency", yearsOfExperience: "6 Years", fees: 5000, rating: 2.5, reviews_number: 134 },
	{ name: "Joseph Williamson", department: "Cardiology-1", yearsOfExperience: "9 Years", fees: 4000, rating: 4.5, reviews_number: 224 },
	{ name: "Prince Williamson", department: "Surgery", yearsOfExperience: "12 Years", fees: 8000, rating: 3.5, reviews_number: 114 },
	{ name: "Prince Ogbonna", department: "Emergency", yearsOfExperience: "6 Years", fees: 5000, rating: 2.5, reviews_number: 134 },
	{ name: "Joseph Williamson", department: "Cardiology-1", yearsOfExperience: "9 Years", fees: 4000, rating: 4.5, reviews_number: 224 },
	{ name: "Prince Williamson", department: "Surgery", yearsOfExperience: "12 Years", fees: 8000, rating: 3.5, reviews_number: 114 },
	{ name: "Prince Ogbonna", department: "Emergency", yearsOfExperience: "6 Years", fees: 5000, rating: 2.5, reviews_number: 134 },
	{ name: "Joseph Williamson", department: "Cardiology-1", yearsOfExperience: "9 Years", fees: 4000, rating: 4.5, reviews_number: 224 },
	{ name: "Christian Nzeanorue", department: "Eye", yearsOfExperience: "8 Years", fees: 7000, rating: 3.0, reviews_number: 14 },
	{ name: "Prince Williamson", department: "Surgery", yearsOfExperience: "12 Years", fees: 8000, rating: 3.5, reviews_number: 114 },
	{ name: "Prince Ogbonna", department: "Emergency", yearsOfExperience: "6 Years", fees: 5000, rating: 2.5, reviews_number: 134 },
	{ name: "Joseph Williamson", department: "Cardiology-1", yearsOfExperience: "9 Years", fees: 4000, rating: 4.5, reviews_number: 224 },
	{ name: "Christian Nzeanorue", department: "Eye", yearsOfExperience: "8 Years", fees: 7000, rating: 3.0, reviews_number: 14 },
	{ name: "Prince Williamson", department: "Surgery", yearsOfExperience: "12 Years", fees: 8000, rating: 3.5, reviews_number: 114 },
	{ name: "Prince Ogbonna", department: "Emergency", yearsOfExperience: "6 Years", fees: 5000, rating: 2.5, reviews_number: 134 },
	{ name: "Joseph Williamson", department: "Cardiology-1", yearsOfExperience: "9 Years", fees: 4000, rating: 4.5, reviews_number: 224 },
	{ name: "Christian Nzeanorue Last", department: "Eye", yearsOfExperience: "8 Years", fees: 7000, rating: 3.0, reviews_number: 14 },
	{ name: "Prince Williamson", department: "Surgery", yearsOfExperience: "12 Years", fees: 8000, rating: 3.5, reviews_number: 114 },
	{ name: "Prince Ogbonna", department: "Emergency", yearsOfExperience: "6 Years", fees: 5000, rating: 2.5, reviews_number: 134 },
	{ name: "Joseph Williamson", department: "Cardiology-1", yearsOfExperience: "9 Years", fees: 4000, rating: 4.5, reviews_number: 224 },
];

export { doctorList };
